export {default as logo} from "./logo.png"
export {default as whatsapp} from "./whatsapp.jpg"
export {default as ourValues} from "./ourvalues.webp"
export {default as ourMission} from "./ourmission.webp"
export {default as shreya} from "./shreya.webp"
export {default as banner} from "./banner.jpg"